### ISSUE TITLE
Add-on ne fonctionne plus : "Allociné erreur"

### ISSUE THREAD

**Issue by nonobio** [jbinard/plugin.video.allocine#2]
Bonjour,

Depuis quelques semaines, l'add-on ne fonctionne plus : chaque tentative d'accès à chacune des sections affiche une notification "Allociné erreur".

Voici un extrait du log Kodi lorsque j'essai d'accéder à "Films Au Cinéma - par date de sortie" : 

`2020-08-20 13:21:14.160 T:16004   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.allocine/?mode=1&name=Films%20Au%20cin%c3%a9ma%20-%20par%20date%20de%20sortie&url=nowshowing)
2020-08-20 13:21:14.160 T:16004   DEBUG:   ParentPath = [plugin://plugin.video.allocine/]
2020-08-20 13:21:14.161 T:8648   DEBUG: Thread waiting start, auto delete: false
2020-08-20 13:21:14.212 T:12668   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.allocine] took 52 ms
2020-08-20 13:21:14.212 T:8648   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Allociné('plugin://plugin.video.allocine/','2','?mode=1&name=Films%20Au%20cin%c3%a9ma%20-%20par%20date%20de%20sortie&url=nowshowing','resume:false')
2020-08-20 13:21:14.212 T:1692   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-08-20 13:21:14.213 T:1692    INFO: initializing python engine.
2020-08-20 13:21:14.213 T:1692   DEBUG: CPythonInvoker(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): start processing
2020-08-20 13:21:14.236 T:1692   DEBUG: -->Python Interpreter Initialized<--
2020-08-20 13:21:14.236 T:1692   DEBUG: CPythonInvoker(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): the source file to load is "C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py"
2020-08-20 13:21:14.236 T:1692   DEBUG: CPythonInvoker(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): setting the Python path to C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
2020-08-20 13:21:14.236 T:1692   DEBUG: CPythonInvoker(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): entering source directory C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine
2020-08-20 13:21:14.236 T:1692   DEBUG: CPythonInvoker(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): instantiating addon using automatically obtained id of "plugin.video.allocine" dependent on version 2.1.0 of the xbmc.python api
2020-08-20 13:21:14.261 T:16004   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-08-20 13:21:14.298 T:1692   DEBUG: CAddonSettings[plugin.video.allocine]: loading setting definitions
2020-08-20 13:21:14.298 T:1692   DEBUG: CAddonSettings[plugin.video.allocine]: trying to load setting definitions from old format...
2020-08-20 13:21:14.298 T:1692   DEBUG: CAddonSettings[plugin.video.allocine]: loading setting values
2020-08-20 13:21:14.299 T:1692   DEBUG: Mode: 1
2020-08-20 13:21:14.299 T:1692   DEBUG: URL: nowshowing
2020-08-20 13:21:14.299 T:1692   DEBUG: Name: Films Au cinéma - par date de sortie
2020-08-20 13:21:14.434 T:1692   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'HTTPError' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py", line 568, in <module>
                                                get_movies_list(url, "datedesc")
                                              File "C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py", line 331, in get_movies_list
                                                result = __getJson(method, query_string)
                                              File "C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py", line 243, in __getJson
                                                except HTTPError, e:
                                            NameError: global name 'HTTPError' is not defined
                                            -->End of Python script error report<--
2020-08-20 13:21:14.434 T:1692   DEBUG: CPythonInvoker::onExecutionDone(16, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py)
2020-08-20 13:21:14.444 T:16004   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-08-20 13:21:14.517 T:1692    INFO: Python interpreter stopped
2020-08-20 13:21:14.517 T:1692   DEBUG: Thread LanguageInvoker 1692 terminating
2020-08-20 13:21:14.533 T:8648   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.allocine/?mode=1&name=Films%20Au%20cin%c3%a9ma%20-%20par%20date%20de%20sortie&url=nowshowing
2020-08-20 13:21:14.533 T:8648   DEBUG: Thread waiting 8648 terminating
2020-08-20 13:21:14.543 T:16004   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-08-20 13:21:14.550 T:16004   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.allocine/?mode=1&name=Films%20Au%20cin%c3%a9ma%20-%20par%20date%20de%20sortie&url=nowshowing) failed
2020-08-20 13:21:14.550 T:16004   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.allocine/)
2020-08-20 13:21:14.550 T:16004   DEBUG:   ParentPath = [plugin://plugin.video.allocine/]
2020-08-20 13:21:14.551 T:18064   DEBUG: Thread waiting start, auto delete: false
2020-08-20 13:21:14.613 T:5964   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.allocine] took 62 ms
2020-08-20 13:21:14.613 T:18064   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Allociné('plugin://plugin.video.allocine/','3','','resume:false')
2020-08-20 13:21:14.614 T:6956   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-08-20 13:21:14.614 T:6956    INFO: initializing python engine.
2020-08-20 13:21:14.614 T:6956   DEBUG: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): start processing
2020-08-20 13:21:14.637 T:6956   DEBUG: -->Python Interpreter Initialized<--
2020-08-20 13:21:14.637 T:6956   DEBUG: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): the source file to load is "C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py"
2020-08-20 13:21:14.637 T:6956   DEBUG: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): setting the Python path to C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
2020-08-20 13:21:14.637 T:6956   DEBUG: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): entering source directory C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine
2020-08-20 13:21:14.637 T:6956   DEBUG: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): instantiating addon using automatically obtained id of "plugin.video.allocine" dependent on version 2.1.0 of the xbmc.python api
2020-08-20 13:21:14.651 T:16004   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-08-20 13:21:14.695 T:6956   DEBUG: CAddonSettings[plugin.video.allocine]: loading setting definitions
2020-08-20 13:21:14.695 T:6956   DEBUG: CAddonSettings[plugin.video.allocine]: trying to load setting definitions from old format...
2020-08-20 13:21:14.696 T:6956   DEBUG: CAddonSettings[plugin.video.allocine]: loading setting values
2020-08-20 13:21:14.696 T:6956   DEBUG: Mode: None
2020-08-20 13:21:14.696 T:6956   DEBUG: URL: None
2020-08-20 13:21:14.696 T:6956   DEBUG: Name: None
2020-08-20 13:21:14.744 T:6956    INFO: CPythonInvoker(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py): script successfully run
2020-08-20 13:21:14.744 T:6956   DEBUG: CPythonInvoker::onExecutionDone(17, C:\Users\mbmc\AppData\Roaming\Kodi\addons\plugin.video.allocine\allocine.py)
2020-08-20 13:21:14.744 T:18064   DEBUG: Thread waiting 18064 terminating
2020-08-20 13:21:14.759 T:16004   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-08-20 13:21:14.787 T:6996   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-08-20 13:21:14.830 T:6996   DEBUG: Thread BackgroundLoader 6996 terminating
2020-08-20 13:21:14.855 T:6956    INFO: Python interpreter stopped
2020-08-20 13:21:14.855 T:6956   DEBUG: Thread LanguageInvoker 6956 terminating
2020-08-20 13:21:19.610 T:16004   DEBUG: ------ Window Init (Pointer.xml) ------
2020-08-20 13:21:20.528 T:16004   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2020-08-20 13:21:25.627 T:16004   DEBUG: ------ Window Deinit (Pointer.xml) ------`

Serait-ce possible de réparer ce problème ? Le développement de l'add-on est il toujours suivi ?

Merci

**Comment by nonobio** [comment]
[allocine.zip](https://github.com/jbinard/plugin.video.allocine/files/5112028/allocine.zip)

J'ai l'impression d'être tout seul sur ce github mais si ça peut servir le problème est résolu grace à gromez : 
Github allociné api gromez :  https://github.com/gromez/allocine-api
Wiki allociné api gromez :  https://wiki.gromez.fr/dev/api/allocine_v3

Je cite : "J'ai vu que c'était la méthode __get_signed_url à modifier, ça ne devrait pas être trop compliqué normalement. "

Il m'a modifié le fichier allocine.py que j'ai mis dans C:\Users\_nonobio_\AppData\Roaming\Kodi\addons\plugin.video.allocine et ça fonctionne !

A+
